/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Array */

#ifndef _Included_Array
#define _Included_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Array
 * Method:    passValue
 * Signature: (II)[C
 */
JNIEXPORT jcharArray JNICALL Java_Array_passValue
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
